_wandb:
    value:
        cli_version: 0.27.2
        e:
            co7gitmok8jdkjp6wu35pn571mj0uxie:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 6
                cpu_count_logical: 8
                disk:
                    /:
                        total: "308302311424"
                        used: "279117004800"
                email: nashrahjaan53@gmail.com
                executable: C:\Users\malik\code-finetune\venv\Scripts\python.exe
                git:
                    commit: 5c93a7be92b8553b7cd95656259bf1671cd41114
                    remote: https://github.com/nashrahjaan53-code/code-finetune.git
                host: lenovo
                memory:
                    total: "8301043712"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\malik\code-finetune\src\train.py
                python: CPython 3.11.9
                root: C:\Users\malik\code-finetune
                startedAt: "2026-06-22T06:06:25.789572Z"
                writerId: co7gitmok8jdkjp6wu35pn571mj0uxie
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 13
            "4": 3.11.9
            "5": 0.27.2
            "6": 4.38.2
            "8":
                - 3
            "12": 0.27.2
            "13": windows-amd64
