_wandb:
    value:
        cli_version: 0.27.2
        e:
            tlbtuzbkhdbuwnsvoc4ojc2g820dx1g8:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 6
                cpu_count_logical: 8
                disk:
                    /:
                        total: "308302311424"
                        used: "286677213184"
                email: nashrahjaan53@gmail.com
                executable: C:\Users\malik\code-finetune\venv\Scripts\python.exe
                git:
                    commit: 61b03f0985cdb204babfcca68ca1b75830f62279
                    remote: https://github.com/nashrahjaan53-code/code-finetune.git
                host: lenovo
                memory:
                    total: "8301043712"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\malik\code-finetune\src\train.py
                python: CPython 3.11.9
                root: C:\Users\malik\code-finetune
                startedAt: "2026-06-22T13:37:09.976202Z"
                writerId: tlbtuzbkhdbuwnsvoc4ojc2g820dx1g8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 13
            "4": 3.11.9
            "5": 0.27.2
            "6": 5.12.1
            "8":
                - 3
            "12": 0.27.2
            "13": windows-amd64
